// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NewSharkPost { user_id: string, img: string, title: string, location_latitude?: number, location_longitude?: number, description: string, }