// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SerializedSharkPost { id: bigint, user_id: string, title: string, images: Array<bigint>, location_latitude?: number, location_longitude?: number, description: string, created_at: string, updated_at?: string, }