// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SharkPost { id: bigint, user_id: string, img_url: string, title: string, location_latitude: number, location_longitude: number, description: string, created_at: string, updated_at: string, }