// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SharkImage { id: bigint, post_id: bigint, file_name?: string, created_at: string, }