// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SharkComment { id: bigint, post_id: bigint, reply_to: bigint, user_ip: string, content: string, created_at: string, updated_at: string, }