// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SharkPost { id: bigint, user_id: bigint, img_url: string, title: string, location: string, description: string, created_at: string, updated_at: string, }